### ISSUE TITLE
week2 95 nedeni

### ISSUE THREAD

**Issue by Pamir** [talhatepe/pyhton-lectures#1]
1. ödevde 4950 diye sabit sayıdan çıkarmışsın. Benim istediğim o toplamı for döngüsü ile bulman. Şimdi sınavda 100 değil de 150 desem oraya kadar tüm sayıları mı toplayacaksın ??

**Comment by talhatepe** [comment]
For ile yaptım tekrar bakabilirseniz güzel olur.
